ARM.imx51 Freescale:ENGR00113366 MX27ads: Fix compiling error
This error is caused by ENGR00093265
error: conflicting types for 'mxc_dma_request_ext' between
dma_mx2.c and dma.h

Signed-off-by: Wallace Wang <r59996@freescale.com>
Signed-off-by: Brad Figg <brad.figg@canonical.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>